version: "3.8"

services:
  swiss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swiss
    ports:
      - "127.0.0.1:8498:8080"
    volumes:
      - ./swiss:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: ["/bin/sh", "-c", "npm install && npm run dev -- --host"]
